### ISSUE TITLE
Panic when run `pkill -USR1 nwg-drawer`

### ISSUE THREAD

**Issue by gouvinb** [nwg-piotr/nwg-drawer#45]
# Description

I have a `nwg-drawer` process in background, and when i run the command `pkill -USR1 nwg-drawer`, `nwg-drawer` panic.

## Actual result

* Run the command `nwg-drawer -fm nautilus -nocats -nofs -o 1 -ovl -r` in a first terminal
* In another terminal run `pkill -USR1 nwg-drawer`
* See nwg-drawer panic.

## Log

```log
INFO[0000] term: foot-direct                            
INFO[0000] lang: fr_FR                                  
INFO[0000] Config dir: /home/gouvinb/.config/nwg-drawer 
INFO[0000] Found 0 pinned items                         
INFO[0000] Found 279 desktop files                      
INFO[0000] Skipped 86 duplicates; 73 .desktop entries hidden by "NoDisplay=true" 
INFO[0000] /home/gouvinb/.config/nwg-drawer/preferred-apps.json file not found 
INFO[0000] /home/gouvinb/.config/nwg-drawer/excluded-dirs file not found 

(nwg-drawer:30966): Gtk-WARNING **: 09:20:51.269: Unknown key gtk-monospace-font-name in /home/gouvinb/.config/gtk-3.0/settings.ini
INFO[0000] Using style from /home/gouvinb/.config/nwg-drawer/drawer.css 
WARN[0000] Undefined icon for XDvi                      
INFO[0000] Using XDG user dirs from /home/gouvinb/.config/user-dirs.dirs 

** (nwg-drawer:30966): WARNING **: 09:20:51.909: gtk-layer-shell v0.6.0 may not work on GTK v3.24.31. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
INFO[0000] UI created in 807 ms. Thank you for your patience. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55cd4496c7e4]

goroutine 1 [running]:
main.main.func6()
	./main.go:498 +0x64
reflect.Value.call({0x55cd44a25e60, 0xc0000d5490, 0xc0001cd7e0}, {0x55cd449a4250, 0x4}, {0x0, 0x0, 0xc000080400})
	reflect/value.go:556 +0x845
reflect.Value.Call({0x55cd44a25e60, 0xc0000d5490, 0x81}, {0x0, 0x0, 0x0})
	reflect/value.go:339 +0xc5
github.com/gotk3/gotk3/glib.sourceFunc(0xc0000001a0)
	github.com/gotk3/gotk3@v0.6.1/glib/glib.go:324 +0xb2
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17413 +0x45
github.com/gotk3/gotk3/gtk.Main(...)
	github.com/gotk3/gotk3@v0.6.1/gtk/gtk.go:1241
main.main()
	./main.go:531 +0x1b05
```

**Comment by nwg-piotr** [comment]
Thank you. I overlooked this crash, since I never use the `-nofs` argument. Let's fix it.

**Comment by gouvinb** [comment]
Hi!

I have a crash again with the same command.

My configuration has not changed.

Here are the logs:

```
time="2022-10-24T13:54:42+02:00" level=info msg="term: foot"
time="2022-10-24T13:54:42+02:00" level=info msg="lang: fr_FR"
time="2022-10-24T13:54:42+02:00" level=info msg="Config dir: /home/gouvinb/.config/nwg-drawer"
time="2022-10-24T13:54:42+02:00" level=info msg="Found 0 pinned items"
time="2022-10-24T13:54:42+02:00" level=info msg="Found 316 desktop files"
time="2022-10-24T13:54:42+02:00" level=info msg="Skipped 76 duplicates; 85 .desktop entries hidden by \"NoDisplay=true\""
time="2022-10-24T13:54:42+02:00" level=info msg="/home/gouvinb/.config/nwg-drawer/preferred-apps.json file not found"
time="2022-10-24T13:54:42+02:00" level=info msg="/home/gouvinb/.config/nwg-drawer/excluded-dirs file not found"
time="2022-10-24T13:54:42+02:00" level=info msg="Preferring dark theme variants"
time="2022-10-24T13:54:42+02:00" level=info msg="Using style from /home/gouvinb/.config/nwg-drawer/drawer.css"
time="2022-10-24T13:54:42+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:54:42+02:00" level=info msg="Using XDG user dirs from /home/gouvinb/.config/user-dirs.dirs"

** (nwg-drawer:968271): WARNING **: 13:54:42.817: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
time="2022-10-24T13:54:42+02:00" level=info msg="UI created in 296 ms. Thank you for your patience."
time="2022-10-24T13:54:58+02:00" level=info msg="env vars: []; command: '/usr/bin/google-chrome-stable'; args: []\n"
time="2022-10-24T13:54:58+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:54:58+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:55:10+02:00" level=info msg="env vars: []; command: '/usr/bin/slack'; args: [-s]\n"
time="2022-10-24T13:55:10+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:55:10+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:55:20+02:00" level=info msg="env vars: []; command: '/home/gouvinb/.local/share/JetBrains/Toolbox/apps/Fleet/ch-0/1.9.237/bin/Fleet'; args: []\n"
time="2022-10-24T13:55:21+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:55:21+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:56:30+02:00" level=info msg="env vars: [--profile-directory=Work --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan]; command: '/opt/google/chrome/google-chrome'; args: [--profile-directory=Work --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan]\n"
time="2022-10-24T13:56:30+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T13:56:31+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T14:02:29+02:00" level=info msg="env vars: [XDG_CURRENT_DESKTOP=gnome]; command: '/usr/bin/zoom'; args: []\n"
time="2022-10-24T14:02:29+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T14:02:29+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T14:04:10+02:00" level=info msg="env vars: [--enable-features=UseOzonePlatform --ozone-platform=wayland]; command: 'signal-desktop'; args: [--use-tray-icon --enable-features=UseOzonePlatform --ozone-platform=wayland --]\n"
time="2022-10-24T14:04:10+02:00" level=warning msg="Undefined icon for XDvi"
time="2022-10-24T14:04:10+02:00" level=warning msg="Undefined icon for XDvi"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f963b8b0239]

runtime stack:
runtime.throw({0x558b4d603e7b?, 0x292?})
	runtime/panic.go:1047 +0x5f fp=0x7f95d20aea70 sp=0x7f95d20aea40 pc=0x558b4d47acbf
runtime.sigpanic()
	runtime/signal_unix.go:819 +0x369 fp=0x7f95d20aeac0 sp=0x7f95d20aea70 pc=0x558b4d490989

goroutine 7 [syscall]:
runtime.cgocall(0x558b4d5f2c60, 0xc000050e48)
	runtime/cgocall.go:158 +0x5c fp=0xc000050e20 sp=0xc000050de8 pc=0x558b4d4497bc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_widget_hide(0x7f95f805c510)
	_cgo_gotypes.go:34354 +0x45 fp=0xc000050e48 sp=0xc000050e20 pc=0x558b4d551205
github.com/gotk3/gotk3/gtk.(*Widget).Hide.func1(0x558b4d4e96b7?)
	github.com/gotk3/gotk3@v0.6.1/gtk/widget.go:258 +0x3f fp=0xc000050e80 sp=0xc000050e48 pc=0x558b4d56cadf
github.com/gotk3/gotk3/gtk.(*Widget).Hide(0xc000100c00?)
	github.com/gotk3/gotk3@v0.6.1/gtk/widget.go:258 +0x19 fp=0xc000050e98 sp=0xc000050e80 pc=0x558b4d56ca79
main.restoreStateAndHide()
	./main.go:580 +0x4b fp=0xc000050f28 sp=0xc000050e98 pc=0x558b4d5bfccb
main.main.func1()
	./main.go:175 +0x16a fp=0xc000050fe0 sp=0xc000050f28 pc=0x558b4d5bfb4a
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000050fe8 sp=0xc000050fe0 pc=0x558b4d4aad01
created by main.main
	./main.go:159 +0x22a

goroutine 1 [syscall]:
runtime.cgocall(0x558b4d5dfde0, 0xc000387a88)
	runtime/cgocall.go:158 +0x5c fp=0xc000387a60 sp=0xc000387a28 pc=0x558b4d4497bc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17432 +0x45 fp=0xc000387a88 sp=0xc000387a60 pc=0x558b4d54dee5
github.com/gotk3/gotk3/gtk.Main(...)
	github.com/gotk3/gotk3@v0.6.1/gtk/gtk.go:1241
main.main()
	./main.go:575 +0x1d6d fp=0xc000387f80 sp=0xc000387a88 pc=0x558b4d5bf12d
runtime.main()
	runtime/proc.go:250 +0x213 fp=0xc000387fe0 sp=0xc000387f80 pc=0x558b4d47d513
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000387fe8 sp=0xc000387fe0 pc=0x558b4d4aad01

goroutine 2 [force gc (idle), 2 minutes]:
runtime.gopark(0xca83452f0d4?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00004efb0 sp=0xc00004ef90 pc=0x558b4d47d8d6
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.forcegchelper()
	runtime/proc.go:302 +0xad fp=0xc00004efe0 sp=0xc00004efb0 pc=0x558b4d47d76d
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00004efe8 sp=0xc00004efe0 pc=0x558b4d4aad01
created by runtime.init.6
	runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00004f790 sp=0xc00004f770 pc=0x558b4d47d8d6
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:297 +0xd7 fp=0xc00004f7c8 sp=0xc00004f790 pc=0x558b4d46a2d7
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc00004f7e0 sp=0xc00004f7c8 pc=0x558b4d45ef26
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00004f7e8 sp=0xc00004f7e0 pc=0x558b4d4aad01
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc745cb6bf11?, 0x10dbad?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00004ff70 sp=0xc00004ff50 pc=0x558b4d47d8d6
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.(*scavengerState).park(0x558b4d85bce0)
	runtime/mgcscavenge.go:389 +0x53 fp=0xc00004ffa0 sp=0xc00004ff70 pc=0x558b4d468333
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:622 +0x65 fp=0xc00004ffc8 sp=0xc00004ffa0 pc=0x558b4d468925
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc00004ffe0 sp=0xc00004ffc8 pc=0x558b4d45eec6
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00004ffe8 sp=0xc00004ffe0 pc=0x558b4d4aad01
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xc00036c000?, 0x0?, 0xa0?, 0x1000000010?)
	runtime/proc.go:363 +0xd6 fp=0xc00004e628 sp=0xc00004e608 pc=0x558b4d47d8d6
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.runfinq()
	runtime/mfinal.go:180 +0x10f fp=0xc00004e7e0 sp=0xc00004e628 pc=0x558b4d45e02f
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x558b4d4aad01
created by runtime.createfing
	runtime/mfinal.go:157 +0x45

goroutine 6 [select, 11 minutes, locked to thread]:
runtime.gopark(0xc0000507a8?, 0x2?, 0x57?, 0xdc?, 0xc0000507a4?)
	runtime/proc.go:363 +0xd6 fp=0xc00005ce18 sp=0xc00005cdf8 pc=0x558b4d47d8d6
runtime.selectgo(0xc00005cfa8, 0xc0000507a0, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc00005cf58 sp=0xc00005ce18 pc=0x558b4d48cd5c
runtime.ensureSigM.func1()
	runtime/signal_unix.go:991 +0x1b4 fp=0xc00005cfe0 sp=0xc00005cf58 pc=0x558b4d490e54
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x558b4d4aad01
created by runtime.ensureSigM
	runtime/signal_unix.go:974 +0xbd

goroutine 18 [syscall]:
runtime.notetsleepg(0xffffffffffffffff?, 0xc00004a728?)
	runtime/lock_futex.go:236 +0x34 fp=0xc00004a7a0 sp=0xc00004a768 pc=0x558b4d451854
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f fp=0xc00004a7c0 sp=0xc00004a7a0 pc=0x558b4d4a77ef
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19 fp=0xc00004a7e0 sp=0xc00004a7c0 pc=0x558b4d511cb9
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00004a7e8 sp=0xc00004a7e0 pc=0x558b4d4aad01
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 8 [GC worker (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000051750 sp=0xc000051730 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0000517e0 sp=0xc000051750 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000517e8 sp=0xc0000517e0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 9 [GC worker (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000051f50 sp=0xc000051f30 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000051fe0 sp=0xc000051f50 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 34 [GC worker (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020a750 sp=0xc00020a730 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020a7e0 sp=0xc00020a750 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020a7e8 sp=0xc00020a7e0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 35 [GC worker (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020af50 sp=0xc00020af30 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020afe0 sp=0xc00020af50 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020afe8 sp=0xc00020afe0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 36 [GC worker (idle), 11 minutes]:
runtime.gopark(0xc0b81266845?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020b750 sp=0xc00020b730 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020b7e0 sp=0xc00020b750 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020b7e8 sp=0xc00020b7e0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 37 [GC worker (idle), 2 minutes]:
runtime.gopark(0xca834570dbe?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020bf50 sp=0xc00020bf30 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020bfe0 sp=0xc00020bf50 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020bfe8 sp=0xc00020bfe0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 38 [GC worker (idle), 2 minutes]:
runtime.gopark(0xca83457259a?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020c750 sp=0xc00020c730 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020c7e0 sp=0xc00020c750 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020c7e8 sp=0xc00020c7e0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 39 [GC worker (idle), 11 minutes]:
runtime.gopark(0xc080275dc6e?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00020cf50 sp=0xc00020cf30 pc=0x558b4d47d8d6
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00020cfe0 sp=0xc00020cf50 pc=0x558b4d461091
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00020cfe8 sp=0xc00020cfe0 pc=0x558b4d4aad01
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 13 [syscall, 2 minutes]:
syscall.Syscall6(0x1?, 0x0?, 0xc000020240?, 0x20?, 0x558b4d5fa899?, 0xa?, 0xc0000220d0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc0000fbe18 sp=0xc0000fbd90 pc=0x558b4d4df796
os.(*Process).blockUntilWaitable(0xc0002383c0)
	os/wait_waitid.go:32 +0x87 fp=0xc0000fbef0 sp=0xc0000fbe18 pc=0x558b4d4fb0a7
os.(*Process).wait(0xc0002383c0)
	os/exec_unix.go:22 +0x28 fp=0xc0000fbf50 sp=0xc0000fbef0 pc=0x558b4d4f7508
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc000426420)
	os/exec/exec.go:599 +0x4b fp=0xc0000fbfc8 sp=0xc0000fbf50 pc=0x558b4d575beb
main.launch.func1()
	./tools.go:609 +0x1d fp=0xc0000fbfe0 sp=0xc0000fbfc8 pc=0x558b4d5c66dd
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000fbfe8 sp=0xc0000fbfe0 pc=0x558b4d4aad01
created by main.launch
	./tools.go:608 +0x625

goroutine 40 [select]:
runtime.gopark(0xc000061fb0?, 0x2?, 0xb0?, 0x1e?, 0xc000061f8c?)
	runtime/proc.go:363 +0xd6 fp=0xc000061e18 sp=0xc000061df8 pc=0x558b4d47d8d6
runtime.selectgo(0xc000061fb0, 0xc000061f88, 0xc000061fa0?, 0x0, 0xc0003fc000?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc000061f58 sp=0xc000061e18 pc=0x558b4d48cd5c
main.main.func6()
	./main.go:527 +0x6c fp=0xc000061fe0 sp=0xc000061f58 pc=0x558b4d5bf72c
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x558b4d4aad01
created by main.main
	./main.go:525 +0x1d5b

goroutine 41 [chan receive, 11 minutes]:
runtime.gopark(0xc0001c1f40?, 0xc000101c00?, 0xa0?, 0xae?, 0xc000207f28?)
	runtime/proc.go:363 +0xd6 fp=0xc0001aae80 sp=0xc0001aae60 pc=0x558b4d47d8d6
runtime.chanrecv(0xc000194f00, 0x0, 0x1)
	runtime/chan.go:583 +0x49b fp=0xc0001aaf10 sp=0xc0001aae80 pc=0x558b4d44c79b
runtime.chanrecv1(0xc000022810?, 0x0?)
	runtime/chan.go:442 +0x18 fp=0xc0001aaf38 sp=0xc0001aaf10 pc=0x558b4d44c2d8
main.watchFiles()
	./watcher.go:55 +0x139 fp=0xc0001aafe0 sp=0xc0001aaf38 pc=0x558b4d5cb0d9
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0001aafe8 sp=0xc0001aafe0 pc=0x558b4d4aad01
created by main.main
	./main.go:573 +0x1d67

goroutine 50 [syscall, 11 minutes]:
syscall.Syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc00052db18 sp=0xc00052da90 pc=0x558b4d4df796
syscall.Syscall6(0xe8, 0x13, 0xc00052dc14, 0x7, 0xffffffffffffffff, 0x0, 0x0)
	<autogenerated>:1 +0x45 fp=0xc00052db60 sp=0xc00052db18 pc=0x558b4d4dfb45
golang.org/x/sys/unix.EpollWait(0x0?, {0xc00052dc14?, 0x0?, 0x0?}, 0x0?)
	golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/unix/zsyscall_linux_amd64.go:77 +0x58 fp=0xc00052dbd0 sp=0xc00052db60 pc=0x558b4d5312d8
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000518000)
	github.com/fsnotify/fsnotify@v1.5.1/inotify_poller.go:87 +0x7d fp=0xc00052dc80 sp=0xc00052dbd0 pc=0x558b4d5bcafd
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00023c0f0)
	github.com/fsnotify/fsnotify@v1.5.1/inotify.go:193 +0x275 fp=0xc00053dfc8 sp=0xc00052dc80 pc=0x558b4d5bbdd5
github.com/fsnotify/fsnotify.NewWatcher.func1()
	github.com/fsnotify/fsnotify@v1.5.1/inotify.go:60 +0x26 fp=0xc00053dfe0 sp=0xc00053dfc8 pc=0x558b4d5bb706
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00053dfe8 sp=0xc00053dfe0 pc=0x558b4d4aad01
created by github.com/fsnotify/fsnotify.NewWatcher
	github.com/fsnotify/fsnotify@v1.5.1/inotify.go:60 +0x1c5

goroutine 51 [select, 11 minutes]:
runtime.gopark(0xc000207fb0?, 0x2?, 0xd8?, 0x21?, 0xc000207f5c?)
	runtime/proc.go:363 +0xd6 fp=0xc000207dd0 sp=0xc000207db0 pc=0x558b4d47d8d6
runtime.selectgo(0xc000207fb0, 0xc000207f58, 0xc000207f10?, 0x0, 0x558b4d5cb12a?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc000207f10 sp=0xc000207dd0 pc=0x558b4d48cd5c
main.watchFiles.func1()
	./watcher.go:36 +0xb5 fp=0xc000207fe0 sp=0xc000207f10 pc=0x558b4d5cadd5
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000207fe8 sp=0xc000207fe0 pc=0x558b4d4aad01
created by main.watchFiles
	./watcher.go:34 +0x12d

goroutine 52 [syscall, 11 minutes]:
syscall.Syscall6(0xc0002077b0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc000207618 sp=0xc000207590 pc=0x558b4d4df796
os.(*Process).blockUntilWaitable(0xc00040f3b0)
	os/wait_waitid.go:32 +0x87 fp=0xc0002076f0 sp=0xc000207618 pc=0x558b4d4fb0a7
os.(*Process).wait(0xc00040f3b0)
	os/exec_unix.go:22 +0x28 fp=0xc000207750 sp=0xc0002076f0 pc=0x558b4d4f7508
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc0001de000)
	os/exec/exec.go:599 +0x4b fp=0xc0002077c8 sp=0xc000207750 pc=0x558b4d575beb
main.launch.func1()
	./tools.go:609 +0x1d fp=0xc0002077e0 sp=0xc0002077c8 pc=0x558b4d5c66dd
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0002077e8 sp=0xc0002077e0 pc=0x558b4d4aad01
created by main.launch
	./tools.go:608 +0x625

goroutine 42 [syscall, 11 minutes]:
syscall.Syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc000208618 sp=0xc000208590 pc=0x558b4d4df796
os.(*Process).blockUntilWaitable(0xc00057a690)
	os/wait_waitid.go:32 +0x87 fp=0xc0002086f0 sp=0xc000208618 pc=0x558b4d4fb0a7
os.(*Process).wait(0xc00057a690)
	os/exec_unix.go:22 +0x28 fp=0xc000208750 sp=0xc0002086f0 pc=0x558b4d4f7508
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc000426000)
	os/exec/exec.go:599 +0x4b fp=0xc0002087c8 sp=0xc000208750 pc=0x558b4d575beb
main.launch.func1()
	./tools.go:609 +0x1d fp=0xc0002087e0 sp=0xc0002087c8 pc=0x558b4d5c66dd
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0002087e8 sp=0xc0002087e0 pc=0x558b4d4aad01
created by main.launch
	./tools.go:608 +0x625

goroutine 43 [syscall, 11 minutes]:
syscall.Syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc000208e18 sp=0xc000208d90 pc=0x558b4d4df796
os.(*Process).blockUntilWaitable(0xc00057b8f0)
	os/wait_waitid.go:32 +0x87 fp=0xc000208ef0 sp=0xc000208e18 pc=0x558b4d4fb0a7
os.(*Process).wait(0xc00057b8f0)
	os/exec_unix.go:22 +0x28 fp=0xc000208f50 sp=0xc000208ef0 pc=0x558b4d4f7508
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc000426160)
	os/exec/exec.go:599 +0x4b fp=0xc000208fc8 sp=0xc000208f50 pc=0x558b4d575beb
main.launch.func1()
	./tools.go:609 +0x1d fp=0xc000208fe0 sp=0xc000208fc8 pc=0x558b4d5c66dd
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000208fe8 sp=0xc000208fe0 pc=0x558b4d4aad01
created by main.launch
	./tools.go:608 +0x625

goroutine 45 [syscall, 4 minutes]:
syscall.Syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	syscall/syscall_linux.go:90 +0x36 fp=0xc0000fde18 sp=0xc0000fdd90 pc=0x558b4d4df796
os.(*Process).blockUntilWaitable(0xc00040f650)
	os/wait_waitid.go:32 +0x87 fp=0xc0000fdef0 sp=0xc0000fde18 pc=0x558b4d4fb0a7
os.(*Process).wait(0xc00040f650)
	os/exec_unix.go:22 +0x28 fp=0xc0000fdf50 sp=0xc0000fdef0 pc=0x558b4d4f7508
os.(*Process).Wait(...)
	os/exec.go:132
os/exec.(*Cmd).Wait(0xc0004262c0)
	os/exec/exec.go:599 +0x4b fp=0xc0000fdfc8 sp=0xc0000fdf50 pc=0x558b4d575beb
main.launch.func1()
	./tools.go:609 +0x1d fp=0xc0000fdfe0 sp=0xc0000fdfc8 pc=0x558b4d5c66dd
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000fdfe8 sp=0xc0000fdfe0 pc=0x558b4d4aad01
created by main.launch
	./tools.go:608 +0x625
```

**Comment by nwg-piotr** [comment]
Couldn't reproduce so far. Could you try an pin at least one icon, and tell me if it still crashes?

**Comment by gouvinb** [comment]
The crash happens randomly, but it happens quite often, I will try to reproduce the bug with a pin item.

**Comment by gouvinb** [comment]
If I pin one item, nwg-drawer doesn't crash.

I don't know if that helped.

**Comment by nwg-piotr** [comment]
Well, it makes no difference on my side. It doesn't crash one way or another.

**Comment by nwg-piotr** [comment]
Could you build from the `fix-45-revisited` branch and check if it still crashes on your side?

**Comment by gouvinb** [comment]
I've been testing all morning and haven't had a crash. It looks good to me! :smile:

**Comment by nwg-piotr** [comment]
If it confirms, I'll merge tonight. Thanks :)
